let text ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque arcu ligula, molestie non suscipit nec, gravida eget odio. Quisque non arcu ac ante pharetra viverra et sit amet lorem. Vivamus mattis, diam in elementum efficitur, sem lacus condimentum metus, eu rutrum sem velit non tortor. Mauris porta quam sit amet porta rutrum. Cras fermentum, sapien ut ullamcorper interdum, lectus neque ultricies ex, vel varius mauris ipsum et justo. Quisque scelerisque orci nisi, sit amet vehicula nisi ornare a. Sed sagittis ut nisi accumsan gravida. Suspendisse vehicula velit sed leo consequat lobortis. Praesent vel dapibus augue, et ultrices libero. Morbi leo massa, tincidunt at risus interdum, luctus suscipit nibh. Nulla nec lectus accumsan, congue augue eget, scelerisque nisl. Phasellus lectus enim, consectetur sit amet felis eu, mollis vehicula leo.

Cras iaculis ipsum diam, id lobortis mauris congue non. Sed mollis, risus nec lacinia dignissim, tortor nunc dapibus est, eget rutrum purus velit in odio. Aenean semper blandit sem, id tristique massa iaculis ac. In quis volutpat ligula. Proin quis urna arcu. Mauris pharetra sodales massa, pellentesque fermentum risus bibendum vel. Fusce in turpis quis turpis scelerisque luctus. Pellentesque eu varius sapien. Praesent non ultrices ipsum. Cras metus ante, molestie eget condimentum nec, varius non nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc quis ligula finibus nisl vestibulum molestie. Sed bibendum leo nec velit scelerisque blandit. Donec tincidunt velit a lacus molestie, ac sagittis magna finibus. Morbi porttitor lectus ornare, rutrum eros sed, laoreet ligula. Ut scelerisque leo ac mauris dapibus, et elementum neque tempor.

Nunc maximus nibh sollicitudin nulla venenatis, quis malesuada turpis tempus. Quisque ultricies magna vel nisi scelerisque, euismod commodo orci ultrices. Ut facilisis rhoncus orci vel cursus. Nunc ultrices hendrerit venenatis. Quisque maximus dui at tincidunt sagittis. Donec ipsum leo, ultricies tempor nibh semper, rhoncus lacinia erat. Vestibulum mattis condimentum vehicula. Suspendisse gravida justo ligula, dictum pellentesque erat laoreet non. Integer finibus ut nisi quis suscipit. Nulla facilisi. Suspendisse vestibulum erat a iaculis egestas. Nam pretium ultricies vehicula. Ut semper felis nec nunc vehicula dapibus. Proin ut risus neque. Nam sit amet turpis nec massa rhoncus sodales non congue dolor. Donec blandit, sapien ut fermentum fermentum, velit arcu volutpat arcu, vel cursus erat nisl a mauris."

let result = text.split(" ").length;
console.log(result);

let etCount = text.split("et").length
console.log(etCount);